---
name: google-oauth2
version: 0.3.0.0
synopsis: Google OAuth2 token negotiation
description: See https://github.com/pbrisbin/google-oauth2#readme
author: Pat Brisbin <pbrisbin@gmail.com>
maintainer: Pat Brisbin <pbrisbin@gmail.com>
license: MIT
github: pbrisbin/google-oauth2

dependencies:
  - base >=4 && <5
  - bytestring
  - hoauth2
  - text
  - time
  - http-client-tls
  - safe-exceptions
  - transformers
  - uri-bytestring
  - time
  - vector
  - filepath
  - directory
  - http-conduit
ghc-options: -Wall

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - google-oauth2
      - hspec
      - http-conduit
      - load-env

executables:
  get-fit:
    source-dirs: app
    main: Main.hs
    dependencies:
      - google-oauth2
      - aeson
